openapi: 3.0.1
info:
  title: Image Compressor
  description: Image compressor OpenAPI implementation
  contact:
    email: 13520103@std.stei.itb.ac.id
  version: 1.0.0
servers:
- url: /v1
tags:
- name: compress
  description: Compress image.
paths:
  /compress:
    post:
      tags:
      - compress
      summary: Compress image with SVD algorithm.
      description: Compress an image from client with provided **_cutting-edge_*** technology of SVD algorithm.

        > \* This is a joke.
      operationId: api.compress
      requestBody:
        content:
          multipart/form-data:
            schema:
              required:
              - imageFile
              - eigenRatio
              - scale
              type: object
              properties:
                imageFile:
                  type: string
                  format: binary
                eigenRatio:
                  type: number
                  minimum: 0
                  maximum: 1
                scale:
                  type: integer
                  maximum: 100
                  minimum: 1
        required: true
      responses:
        200:
          description: Return the compressed image.
          content:
            image/*:
              schema:
                type: string
                format: binary
        400:
          $ref: '#/components/responses/RequestError'
        500:
          $ref: '#/components/responses/InternalServerError'
components:
  schemas:
    ModelErrorResponse:
      type: object
      properties:
        message:
          type: string
          description: Error message
  responses:
    RequestError:
      description: Input invalid or not specified
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/ModelErrorResponse'
          examples:
            Invalid Input Error:
              $ref: '#/components/examples/InvalidInputError'
            Invalid Request Error:
              $ref: '#/components/examples/InvalidRequestError'
            Bad Request:
              $ref: '#/components/examples/InvalidBodyType'
    InternalServerError:
      description: Internal server error
      content:
        application/json:
          schema:
            type: object
          example: {
            "type": "about:blank",
            "title": "Internal Server Error",
            "detail": "The server encountered an internal error and was unable to complete your request. Either the server is overloaded or there is an error in the application.",
            "status": 500
          }
  examples:
    InvalidInputError:
      value: { "message": "Invalid Input" }
    InvalidRequestError:
      value: { "message": "Invalid Request" }
    InvalidBodyType:
      value: {
        "type": "about:blank",
        "title": "Bad Request",
        "detail": "Request body is not valid JSON",
        "status": 400
      }
    NoAuthToken:
      value: {
        "type": "about:blank",
        "title": "Unauthorized",
        "detail": "No authorization token provided",
        "status": 401
      }
    InvalidAuthToken:
      value: {
        "type": "about:blank",
        "title": "Unauthorized",
        "detail": "The server could not verify that you are authorized to access the URL requested. You either supplied the wrong credentials (e.g. a bad password), or your browser doesn't understand how to supply the credentials required.",
        "status": 401
      }
