openapi: 3.0.1
info:
  title: ImaGeprek
  description: Image compressor (geprek) OpenAPI implementation
  contact:
    email: 13520103@std.stei.itb.ac.id
  version: 1.0.0
servers:
- url: /v1
tags:
- name: compress
  description: Compress image.
paths:
  /compress:
    post:
      tags:
      - compress
      summary: Compress image with SVD algorithm.
      description: Compress an image from client with provided **_cutting-edge_*** technology of SVD algorithm.

        > \* This is a joke.
      operationId: api.compress
      requestBody:
        content:
          multipart/form-data:
            schema:
              required:
              - imageFile
              type: object
              properties:
                imageFile:
                  type: string
                  format: binary
                eigenRatio:
                  type: number
                  default: 0.2
                  minimum: 0
                  maximum: 1
                scale:
                  type: integer
                  default: 100
                  maximum: 100
                  minimum: 1
                preserveAlpha:
                  type: boolean
                  default: True
                iteration:
                  type: integer
                  default: 2
                  maximum: 100
                  minimum: 2
        required: true
      responses:
        200:
          description: Return the compressed image.
          content:
            image/*:
              schema:
                type: string
                format: binary
        400:
          $ref: '#/components/responses/RequestError'
        500:
          $ref: '#/components/responses/InternalServerError'
components:
  schemas:
    ModelErrorResponse:
      type: object
      properties:
        message:
          type: string
          description: Error message
  responses:
    RequestError:
      description: Input invalid or missing
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/ModelErrorResponse'
          examples:
            Invalid Input Error:
              $ref: '#/components/examples/InvalidInputError'
            Invalid Request Error:
              $ref: '#/components/examples/InvalidRequestError'
    InternalServerError:
      description: Internal server error
      content:
        application/json:
          schema:
            type: object
          example: {
            "type": "about:blank",
            "title": "Internal Server Error",
            "detail": "The server encountered an internal error and was unable to complete your request. Either the server is overloaded or there is an error in the application.",
            "status": 500
          }
  examples:
    InvalidInputError:
      value: {
        "message": "Invalid Input",
        "details": "<input error details>",
        "status": 400
      }
    InvalidRequestError:
      value: { 
        'message': 'Missing parameters',
        'details': 'imageFile should exist',
        'status': 400
      }
